title: Grav
author:
  name: Joe Bloggs
  email: 'joe@test.com'
blog:
  route: ''
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'

sidebar_widget:
  title: Some Text Widget
  body: Lorem ipsum **dolor sit amet**, consectetur adipisicing elit, sed do eiusmod tempor [incididunt](#) ut labore et dolore magna.

taxonomies: [category,tag,month]
redirects:
    /changelog: /blog/the-urban-jungle
routes:
    /something/else: /blog/focus-and-blur
    /another/one/(.*): /blog/$1

